import { PERMISSIONS } from "./Permissions";
import { ROLES } from "./roles";

export const ROLE_PERMISSIONS = {
  [ROLES.CONTENT_MANAGER]: [
    PERMISSIONS.POSTS_VIEW,
    PERMISSIONS.POSTS_CREATE,
    PERMISSIONS.POSTS_EDIT,
    PERMISSIONS.POSTS_DELETE,
    PERMISSIONS.COMMENTS_ADD,
  ],

  [ROLES.REVIEWER]: [
    PERMISSIONS.POSTS_VIEW,
    PERMISSIONS.COMMENTS_ADD,
  ],

  [ROLES.READER]: [
    PERMISSIONS.POSTS_VIEW,
  ],
} as const;